# This is a simple Serverless Workflow that will be
# translated into a Temporal workflow
document:
  dsl: 1.0.0
  namespace: ignored # Ignored by Temporal
  name: conditional # Workflow name
  version: 0.0.1
  title: Conditional Workflow
  summary: Execute tasks conditionally
timeout:
  after:
    minutes: 1
do:
  # If input is odd, wait 5 seconds
  - waitIfOdd:
      if: "${ .randomInteger % 2 == 0 }"
      wait:
        seconds: 5
  # If input is even, wait 10 seconds
  - waitIfEven:
      if: "${ .randomInteger % 2 == 1 }"
      wait:
        seconds: 10
  # Always wait 5 seconds at the end
  - wait:
      wait:
        seconds: 5
