document:
  dsl: 1.0.0
  namespace: temporal-dsl # Mapped to the task queue
  name: export # Workflow name
  version: 0.0.1
  title: Export Data
  summary: How to configure the data export
timeout:
  after:
    minutes: 1
do:
  # Returns { "data1": { "key1" : "value1", "key2": "value2" } }
  - data1:
      set:
        data1:
          key1: value1
          key2: value2
      export:
        as: ${ . }
  # Returns { "data2": { "key1": "value1", "key2": "value2" }, "input": { "shouldCall": true } }
  - data2:
      set:
        data2: ${ $context.data1 }
        input: ${ $input }
  # { "data4": { "data2": { "key1": "value1", "key2": "value2" }, "input": { "shouldCall": true } } }
  - data3:
      set:
        data4: ${ . }
