header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Temporal DSL authors <https://github.com/mrsimonemms/temporal-dsl/graphs/contributors>
    copyright-year: 2025
  paths-ignore:
    - "**/dist"
    - "**/tmp"
    - LICENSE
    - "**/.*"
    - "**/go.*"
    - "**/*.{json,md,yml,yaml,txt}"
    - "**/.gitkeep"
  comment: on-failure
  language:
    Go:
      extensions:
        - ".go"
      comment_style_id: SlashAsterisk

dependency:
  files:
    - go.mod # If this is a Go project.
