# This is a simple Serverless Workflow that will be
# translated into a Temporal workflow
document:
  dsl: 1.0.0
  namespace: ignored # Ignored by Temporal
  name: schedule # Workflow name
  version: 0.0.1
  title: Serverless Workflow
  summary: Schedule the tasks to be triggered automatically
  metadata:
    # Set the workflow name - this will either be the document.name or the Do task (see multiple-workflows example)
    scheduleWorkflowName: schedule
    # Optionally set the schedule ID name
    scheduleId: some-schedule
    # Optionally set any input for the workflow when triggered
    scheduleInput:
      - hello
      - world
timeout:
  after:
    minutes: 1
schedule:
  # Every is support as a Temporal interval - https://pkg.go.dev/go.temporal.io/sdk/client#ScheduleIntervalSpec
  every:
    minutes: 3
  # Cron is support as a Temporal cronjob - timezone is UTC
  cron: "0 0 * * *"
do:
  - wait:
      wait:
        seconds: 5
