apiVersion: v1
kind: Service
metadata:
  name: {{ include "temporal-dsl.fullname" . }}
  labels:
    {{- include "temporal-dsl.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.health.port }}
      targetPort: health
      protocol: TCP
      name: health
    - port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "temporal-dsl.selectorLabels" . | nindent 4 }}
