.anchors:
  notifyReviewer: &notifyReviewer
    call: http
    with:
      # This is a call to a mocked API for testing purposes - in reality, this
      # would be your deployment endpoint or a child workflow
      #
      # @link https://jsonplaceholder.typicode.com/guide
      method: post
      endpoint: https://jsonplaceholder.typicode.com/posts
      headers:
        content-type: application/json
      body:
        title: There is a change for you to review
        body:
          message: Review required.
          changeId: ${ $input.changeId }
        userId: 1

document:
  dsl: 1.0.0
  namespace: temporal-dsl
  name: authoriseChangeRequest # Workflow name
  version: 0.0.1
  title: Authorise Change Request
  summary: Authorise and implement or reject a change request
input:
  schema:
    format: json
    document:
      type: object
      required:
        - changeId
      properties:
        changeId:
          type: string
do:
  # Create get state query
  - queryState:
      listen:
        to:
          one:
            with:
              id: get_state
              type: query
              datacontenttype: application/json
              data:
                id: ${ $data.id }
                approved: ${ $data.approved }
                status: ${ $data.status }
  # Configure the state
  - stateSetup:
      set:
        id: ${ uuid }
        approved: false
        status: starting
  # Start an approval timer and trigger the review
  - startReview:
      fork:
        # First one to finish "wins"
        compete: true
        branches:
          # Auto-approve after 1 minute
          - autoApproval:
              do:
                - timeout:
                    wait:
                      seconds: 60
                # Output the fork's response
                - autoApprove:
                    export:
                      as: review
                    set:
                      approved: true
          # Remind reviewer about the request after 30 seconds - this is designed
          # to never "win"
          - remindReviewer:
              do:
                - timeout:
                    wait:
                      seconds: 30
                - notifyReviewer: *notifyReviewer
                # Continue waiting until autoApprove has fired - realistically, this is infinite
                # as this branch should never "win"
                - timeout:
                    wait:
                      days: 7
          # Listen for the review response
          - waitForApproval:
              do:
                # Notify the reviewer
                - notifyReviewer: *notifyReviewer
                # Listen for the review signal to be triggered
                - review:
                    listen:
                      to:
                        one:
                          with:
                            # Signal name
                            id: review
                            type: signal
                # Output the fork's response
                - set:
                    export:
                      as: review
                    set:
                      # Get response from the signal
                      approved: ${ $data.review.approved }
  # Update the status
  - updateState:
      set:
        status: moderated
        approved: ${ $data.review.approved }
  # If the change has been approved, apply it
  - applyChange:
      if: ${ $data.approved == true }
      call: http
      with:
        # This is a call to a mocked API for testing purposes - in reality, this
        # would be your deployment endpoint or a child workflow
        #
        # @link https://jsonplaceholder.typicode.com/guide
        method: post
        endpoint: https://jsonplaceholder.typicode.com/posts
        headers:
          content-type: application/json
        body:
          title: Approved post
          body:
            message: This post has been approved.
            changeId: ${ $input.changeId }
          userId: 1
  # Notify the end user that the change has been reviewed
  - notifyResult:
      call: http
      with:
        # This is a call to a mocked API for testing purposes - in reality, this
        # would be your deployment endpoint or a child workflow
        #
        # @link https://jsonplaceholder.typicode.com/guide
        method: post
        endpoint: https://jsonplaceholder.typicode.com/posts
        headers:
          content-type: application/json
        body:
          title: Notify user of review
          body:
            message: This post has been reviewed.
            changeId: ${ $input.changeId }
            isApproved: ${ $data.approved }
          userId: 1
