services:
  server:
    build:
      context: ./server
    volumes:
      - ./server:/go/app
    ports:
      - 3000:3000

  searchAttributes:
    image: temporalio/temporal
    environment:
      TEMPORAL_ADDRESS: temporal:7233
    restart: on-failure
    depends_on:
      temporal:
        condition: service_healthy
    command: operator search-attribute create --name Step --type text

  temporal:
    image: temporalio/temporal
    ports:
      - 8080:8233
    command: server start-dev --ip 0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "temporal operator cluster health"]
      interval: 10s
      timeout: 10s
      retries: 3

  workflow:
    build:
      context: ../../
      target: builder
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-debug}"
      TASK_QUEUE: MoneyTransfer
      TEMPORAL_ADDRESS: temporal:7233
      WORKFLOW_FILE: ./examples/money-transfer/workflow.yaml
    volumes:
      - ../../:/go/app
    links:
      - server
      - temporal
    depends_on:
      searchAttributes:
        condition: service_completed_successfully
      temporal:
        condition: service_healthy
      # UI isn't actually linked, but allows us to run docker compose up workflow
      ui:
        condition: service_started

  ui:
    image: ghcr.io/temporal-sa/money-transfer-demo/ui
    links:
      - temporal
    depends_on:
      temporal:
        condition: service_healthy
    ports:
      - 7070:7070
