document:
  dsl: 1.0.0
  namespace: temporal-dsl # Mapped to the task queue
  name: for-loop # Workflow name
  version: 0.0.1
  title: For loops
  summary: An example of how to use the for loop task
input:
  schema:
    format: json
    document:
      type: object
      required:
        - map
        - data
      properties:
        map:
          type: object
          required:
            - key1
            - key2
            - key3
          properties:
            key1:
              type: string
            key2:
              type: number
            key3:
              type: boolean
        data:
          type: array
          items:
            type: object
            required:
              - userId
            properties:
              userId:
                type: number
do:
  # Iterate over the map object
  - forTaskMap:
      export:
        as:
          map: ${ . }
      for:
        in: ${ $input.map }
        at: index # Optional: the loop's key, defaults to "index" available on $data
        each: item # Optional: the loop's value, defaults to "item" available on $data
      do:
        - setData:
            export:
              as: ${ . }
            set:
              key: '${ "hello " + $data.index }'
              value: ${ $data.item }
        - wait:
            output:
              as: ${ $context }
            wait:
              seconds: 1
  # Iterate over the data array
  - forTaskArray:
      output:
        as: '${ $context + { "array": . } }'
      for:
        in: ${ $input.data }
      while: ${ $data.item.userId != 4 } # If this returns false, it will abort the iteration
      do:
        # Each iteration will run these tasks in order
        - setData:
            export:
              as: ${ . }
            set:
              userId: ${ $data.item.userId } # Get the userId for this iteration
              id: ${ $data.index } # Get the key
              processed: true
              uuid: ${ uuid }
        - wait:
            output:
              as: ${ $context }
            wait:
              seconds: 1
