document:
  dsl: 1.0.0
  namespace: default
  name: listen
  version: 0.0.1
  title: Serverless Workflow
  summary: Listen for events
do:
  - callDoctor:
      listen:
        to:
          all:
            - with:
                # ID maps to the update name in Temporal
                id: com.fake-hospital.vitals.measurements.temperature
                # Temporal update - used to make read/write request
                type: update
                # Conditionally accept - numbers are sent as float64 so we need to add ".0" as a float
                if: "{{ gt .temperature 38.0 }}"
            - with:
                id: com.fake-hospital.vitals.measurements.bpm
                type: update
                # You can pass in multiple params
                if: "{{ or (lt .bpm 60.0) (gt .bpm 100.0) }}"
