document:
  dsl: 1.0.0
  namespace: default
  name: signal
  version: 0.0.1
  title: Serverless Workflow
  summary: Listen for events
do:
  - approve:
      listen:
        to:
          one:
            with:
              # ID maps to the query name in Temporal
              id: approve
              # Temporal signal - used to make write request
              type: signal
              # Timeout - runs forever if not sent
              timeout: 10s
  - wait:
      wait:
        seconds: 5
