# This is a simple Serverless Workflow that will be
# translated into a Temporal workflow
document:
  dsl: 1.0.0
  namespace: ignored # Ignored by Temporal
  name: basic # Workflow name
  version: 0.0.1
  title: Serverless Workflow
  summary: An example of how to use Serverless Workflow to define Temporal Workflows
timeout:
  after:
    minutes: 1
do:
  - step1:
      set:
        # Set a variable from an envvar
        envvar: "{{ .TSW_EXAMPLE_ENVVAR }}"
        uuid: "{{ uuidv4 }}"
  - wait:
      wait:
        seconds: 5
  - getUser:
      call: http
      with:
        method: get
        endpoint: https://jsonplaceholder.typicode.com/users/{{ .userId }}
  - raiseAlarm:
      fork:
        compete: false
        branches:
          - callNurse:
              call: http
              with:
                method: get
                endpoint: https://jsonplaceholder.typicode.com/users/1
          - wait:
              wait:
                seconds: 5
          - callDoctor:
              call: http
              with:
                method: get
                endpoint: https://jsonplaceholder.typicode.com/users/3
